### ISSUE TITLE
O app não roda muito bem, a ideia é boa, poderia melhorar algumas coisas e melhorar um pouco o css

### ISSUE THREAD

**Issue by EveeSilvaa** [RibeiroRibas/appagenda#2]
mudar o CSS, esta muito rosa.., fazer algo mais clean 
a ideia é maravilhosa, ajeitar o código também, pois o agendamento não esta rodando bem.

**Comment by RibeiroRibas** [comment]
Oi Evellyn, que bom que você gostou, o app funcionava perfeitamente, ele foi meu portfólio pra entrar na área e tinha algumas pessoas usando, depois que consegui minha vaga não dei mais manutenção. Eu hospedei a api e o banco de dados no hekoru quando era free, depois que ficou pago eu não quis mais manter ele por que não era monetisado. Fiz um revert pra versão 1 que não dependia do servidor, tem uma branch no repositório da versão 1, mas sinceramente não testei todas as funcionalidades pra saber se ta funcionando.
